services:
  - type: web
    name: habit-tracker-api
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --no-cache-dir --prefer-binary -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: habit-tracker-db
          property: connectionString
